import type { AdminWidgetMeta, AdminWidgetType, AdminDashboardLayout } from './types';

export const ADMIN_WIDGET_REGISTRY: Record<AdminWidgetType, AdminWidgetMeta> = {
  'metrics-overview': {
    type: 'metrics-overview',
    title: 'Metrics Overview',
    description: 'Key business metrics at a glance',
    icon: 'BarChart3',
    category: 'overview',
    defaultW: 12,
    defaultH: 3,
    minW: 6,
    minH: 2,
  },
  'revenue-chart': {
    type: 'revenue-chart',
    title: 'Revenue Chart',
    description: 'Revenue trends over time',
    icon: 'DollarSign',
    category: 'analytics',
    defaultW: 6,
    defaultH: 4,
    minW: 4,
    minH: 3,
  },
  'order-volume': {
    type: 'order-volume',
    title: 'Order Volume',
    description: 'Daily order counts',
    icon: 'ShoppingCart',
    category: 'analytics',
    defaultW: 6,
    defaultH: 4,
    minW: 4,
    minH: 3,
  },
  'traffic-chart': {
    type: 'traffic-chart',
    title: 'Traffic Chart',
    description: 'Page views and visitor trends',
    icon: 'TrendingUp',
    category: 'analytics',
    defaultW: 8,
    defaultH: 4,
    minW: 4,
    minH: 3,
  },
  'quick-actions': {
    type: 'quick-actions',
    title: 'Quick Actions',
    description: 'Shortcuts to common tasks',
    icon: 'Zap',
    category: 'actions',
    defaultW: 6,
    defaultH: 3,
    minW: 4,
    minH: 2,
  },
  'recent-orders': {
    type: 'recent-orders',
    title: 'Recent Orders',
    description: 'Latest orders with status',
    icon: 'Package',
    category: 'data',
    defaultW: 6,
    defaultH: 3,
    minW: 4,
    minH: 3,
  },
  'content-stats': {
    type: 'content-stats',
    title: 'Content Stats',
    description: 'Blog posts, pages, and media counts',
    icon: 'FileText',
    category: 'overview',
    defaultW: 4,
    defaultH: 4,
    minW: 3,
    minH: 2,
  },
  'top-products': {
    type: 'top-products',
    title: 'Top Products',
    description: 'Best selling products',
    icon: 'Star',
    category: 'data',
    defaultW: 6,
    defaultH: 3,
    minW: 4,
    minH: 3,
  },
  'conversion-rate': {
    type: 'conversion-rate',
    title: 'Conversion Rate',
    description: 'Visitor to customer conversion',
    icon: 'Target',
    category: 'analytics',
    defaultW: 4,
    defaultH: 3,
    minW: 3,
    minH: 2,
  },
  'customer-growth': {
    type: 'customer-growth',
    title: 'Customer Growth',
    description: 'New customer signups over time',
    icon: 'Users',
    category: 'analytics',
    defaultW: 6,
    defaultH: 4,
    minW: 4,
    minH: 3,
  },
  'system-health': {
    type: 'system-health',
    title: 'System Health',
    description: 'API response times and uptime',
    icon: 'Activity',
    category: 'overview',
    defaultW: 4,
    defaultH: 3,
    minW: 3,
    minH: 2,
  },
};

export function getDefaultAdminLayout(): AdminDashboardLayout {
  return {
    version: 1,
    widgets: [
      { id: 'w-metrics', type: 'metrics-overview', title: 'Metrics Overview', x: 0, y: 0, w: 12, h: 3, visible: true },
      { id: 'w-revenue', type: 'revenue-chart', title: 'Revenue Chart', x: 0, y: 3, w: 6, h: 4, visible: true },
      { id: 'w-orders-vol', type: 'order-volume', title: 'Order Volume', x: 6, y: 3, w: 6, h: 4, visible: true },
      { id: 'w-actions', type: 'quick-actions', title: 'Quick Actions', x: 0, y: 7, w: 6, h: 3, visible: true },
      { id: 'w-recent', type: 'recent-orders', title: 'Recent Orders', x: 6, y: 7, w: 6, h: 3, visible: true },
      { id: 'w-traffic', type: 'traffic-chart', title: 'Traffic Chart', x: 0, y: 10, w: 8, h: 4, visible: true },
      { id: 'w-content', type: 'content-stats', title: 'Content Stats', x: 8, y: 10, w: 4, h: 4, visible: true },
    ],
  };
}
