import type { BlockTemplate, BlockCategory } from "./types"

export const BLOCK_TEMPLATES: BlockTemplate[] = [
  // ========== LAYOUT ==========
  {
    label: "Section",
    tag: "section",
    icon: "LayoutGrid",
    category: "layout",
    defaultClassName: "w-full py-16 px-6",
    isContainer: true,
  },
  {
    label: "Flex Row",
    tag: "div",
    icon: "Columns3",
    category: "layout",
    defaultClassName: "flex flex-row items-center gap-4 p-4",
    isContainer: true,
  },
  {
    label: "Flex Column",
    tag: "div",
    icon: "Rows3",
    category: "layout",
    defaultClassName: "flex flex-col gap-4 p-4",
    isContainer: true,
  },
  {
    label: "Grid 2-Col",
    tag: "div",
    icon: "LayoutGrid",
    category: "layout",
    defaultClassName: "grid grid-cols-2 gap-6 p-4",
    isContainer: true,
  },
  {
    label: "Grid 3-Col",
    tag: "div",
    icon: "LayoutGrid",
    category: "layout",
    defaultClassName: "grid grid-cols-3 gap-6 p-4",
    isContainer: true,
  },
  {
    label: "Container",
    tag: "div",
    icon: "Square",
    category: "layout",
    defaultClassName: "max-w-6xl mx-auto px-6",
    isContainer: true,
  },
  {
    label: "Card",
    tag: "div",
    icon: "RectangleHorizontal",
    category: "layout",
    defaultClassName: "rounded-xl border border-white/10 bg-white/5 p-6 shadow-lg backdrop-blur-sm",
    isContainer: true,
  },
  {
    label: "Header",
    tag: "header",
    icon: "PanelTop",
    category: "layout",
    defaultClassName: "w-full flex items-center justify-between px-6 py-4",
    isContainer: true,
  },
  {
    label: "Footer",
    tag: "footer",
    icon: "PanelBottom",
    category: "layout",
    defaultClassName: "w-full py-8 px-6 border-t border-white/10",
    isContainer: true,
  },
  {
    label: "Nav",
    tag: "nav",
    icon: "Menu",
    category: "layout",
    defaultClassName: "flex items-center gap-6",
    isContainer: true,
  },

  // ========== TYPOGRAPHY ==========
  {
    label: "Heading 1",
    tag: "h1",
    icon: "Type",
    category: "typography",
    defaultClassName: "text-5xl font-bold tracking-tight text-white",
    defaultTextContent: "Heading",
    isContainer: false,
  },
  {
    label: "Heading 2",
    tag: "h2",
    icon: "Type",
    category: "typography",
    defaultClassName: "text-3xl font-semibold tracking-tight text-white",
    defaultTextContent: "Subheading",
    isContainer: false,
  },
  {
    label: "Heading 3",
    tag: "h3",
    icon: "Type",
    category: "typography",
    defaultClassName: "text-xl font-semibold text-white",
    defaultTextContent: "Section title",
    isContainer: false,
  },
  {
    label: "Paragraph",
    tag: "p",
    icon: "AlignLeft",
    category: "typography",
    defaultClassName: "text-base leading-relaxed text-white/70",
    defaultTextContent: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore.",
    isContainer: false,
  },
  {
    label: "Small Text",
    tag: "p",
    icon: "AlignLeft",
    category: "typography",
    defaultClassName: "text-sm text-white/50",
    defaultTextContent: "Small helper text",
    isContainer: false,
  },
  {
    label: "Link",
    tag: "a",
    icon: "Link",
    category: "typography",
    defaultClassName: "text-blue-400 hover:text-blue-300 underline underline-offset-4 transition-colors",
    defaultTextContent: "Click here",
    defaultAttrs: { href: "#" },
    isContainer: false,
  },
  {
    label: "Blockquote",
    tag: "blockquote",
    icon: "Quote",
    category: "typography",
    defaultClassName: "border-l-4 border-white/20 pl-4 italic text-white/60",
    defaultTextContent: "Something worth quoting.",
    isContainer: false,
  },
  {
    label: "Badge",
    tag: "span",
    icon: "Tag",
    category: "typography",
    defaultClassName: "inline-flex items-center rounded-full bg-blue-500/10 px-3 py-1 text-xs font-medium text-blue-400 ring-1 ring-blue-500/20",
    defaultTextContent: "Badge",
    isContainer: false,
  },

  // ========== MEDIA ==========
  {
    label: "Image",
    tag: "img",
    icon: "Image",
    category: "media",
    defaultClassName: "w-full h-60 rounded-lg object-cover",
    defaultAttrs: {
      src: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&q=80",
      alt: "Placeholder image",
    },
    isContainer: false,
  },
  {
    label: "Avatar",
    tag: "img",
    icon: "CircleUser",
    category: "media",
    defaultClassName: "h-12 w-12 rounded-full object-cover ring-2 ring-white/20",
    defaultAttrs: {
      src: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&q=80",
      alt: "Avatar",
    },
    isContainer: false,
  },
  {
    label: "Video",
    tag: "video",
    icon: "Play",
    category: "media",
    defaultClassName: "w-full rounded-lg",
    defaultAttrs: {
      src: "",
      controls: "",
      poster: "",
    },
    isContainer: false,
    description: "Embedded video player with controls",
  },
  {
    label: "Video (Autoplay)",
    tag: "video",
    icon: "Play",
    category: "media",
    defaultClassName: "w-full rounded-lg",
    defaultAttrs: {
      src: "",
      autoplay: "",
      muted: "",
      loop: "",
      playsinline: "",
    },
    isContainer: false,
    description: "Background video — autoplays muted and loops",
  },
  {
    label: "Divider",
    tag: "hr",
    icon: "Minus",
    category: "media",
    defaultClassName: "border-t border-white/10 my-4",
    isContainer: false,
  },
  {
    label: "Spacer",
    tag: "div",
    icon: "MoveVertical",
    category: "media",
    defaultClassName: "h-12",
    isContainer: false,
  },
  {
    label: "Icon Box",
    tag: "div",
    icon: "Sparkles",
    category: "media",
    defaultClassName: "flex h-12 w-12 items-center justify-center rounded-lg bg-blue-500/10 text-blue-400",
    defaultTextContent: "*",
    isContainer: false,
  },

  // ========== INTERACTIVE ==========
  {
    label: "Button",
    tag: "button",
    icon: "MousePointerClick",
    category: "interactive",
    defaultClassName: "rounded-lg bg-blue-600 px-6 py-3 text-sm font-medium text-white hover:bg-blue-500 transition-colors shadow-lg shadow-blue-500/25",
    defaultTextContent: "Get Started",
    isContainer: false,
  },
  {
    label: "Outline Button",
    tag: "button",
    icon: "MousePointerClick",
    category: "interactive",
    defaultClassName: "rounded-lg border border-white/20 px-6 py-3 text-sm font-medium text-white hover:bg-white/5 transition-colors",
    defaultTextContent: "Learn More",
    isContainer: false,
  },
  {
    label: "Ghost Button",
    tag: "button",
    icon: "MousePointerClick",
    category: "interactive",
    defaultClassName: "rounded-lg px-6 py-3 text-sm font-medium text-white/70 hover:text-white hover:bg-white/5 transition-colors",
    defaultTextContent: "Cancel",
    isContainer: false,
  },
  {
    label: "List (UL)",
    tag: "ul",
    icon: "List",
    category: "interactive",
    defaultClassName: "list-disc list-inside space-y-2 text-white/70",
    isContainer: true,
  },
  {
    label: "List Item",
    tag: "li",
    icon: "ListOrdered",
    category: "interactive",
    defaultClassName: "text-sm",
    defaultTextContent: "List item",
    isContainer: false,
  },

  // ========== FORM ==========
  {
    label: "Input",
    tag: "input",
    icon: "TextCursorInput",
    category: "form",
    defaultClassName: "w-full rounded-lg border border-white/10 bg-white/5 px-4 py-3 text-sm text-white placeholder:text-white/30 focus:outline-none focus:ring-2 focus:ring-blue-500/50",
    defaultAttrs: { type: "text", placeholder: "Enter text..." },
    isContainer: false,
  },
  {
    label: "Textarea",
    tag: "textarea",
    icon: "FileText",
    category: "form",
    defaultClassName: "w-full rounded-lg border border-white/10 bg-white/5 px-4 py-3 text-sm text-white placeholder:text-white/30 focus:outline-none focus:ring-2 focus:ring-blue-500/50 min-h-[100px] resize-none",
    defaultAttrs: { placeholder: "Enter longer text..." },
    isContainer: false,
  },
  {
    label: "Label",
    tag: "label",
    icon: "Tag",
    category: "form",
    defaultClassName: "text-sm font-medium text-white/80",
    defaultTextContent: "Label",
    isContainer: false,
  },
  {
    label: "Form",
    tag: "form",
    icon: "FormInput",
    category: "form",
    defaultClassName: "flex flex-col gap-4 w-full",
    isContainer: true,
  },
  {
    label: "Managed Form",
    tag: "div",
    icon: "ClipboardList",
    category: "form",
    defaultClassName: "w-full max-w-xl mx-auto py-8",
    componentName: "FormBlock",
    description: "Renders a form built in Admin → Forms (newsletter, feedback, contact). Set the form slug in properties.",
    defaultAttrs: { "data-form-slug": "" },
    isContainer: false,
  },

  // ========== GENERIC COMMERCE (CMS-bindable) ==========
  {
    label: "Product Card",
    tag: "div",
    icon: "Package",
    category: "commerce",
    defaultClassName: "group flex flex-col gap-3 rounded-xl border border-white/10 bg-white/5 p-4 hover:border-white/20 transition-colors",
    isContainer: true,
    description: "Generic product card - bind to any CMS collection",
    defaultCommerce: { type: "product", provider: "generic" },
  },
  {
    label: "Product Grid",
    tag: "div",
    icon: "Grid3X3",
    category: "commerce",
    defaultClassName: "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6",
    isContainer: true,
    description: "Grid layout for products - bind to CMS collection",
    defaultCommerce: { type: "collection", provider: "generic", limit: 8 },
  },
  {
    label: "Price Display",
    tag: "span",
    icon: "DollarSign",
    category: "commerce",
    defaultClassName: "text-2xl font-bold text-white",
    defaultTextContent: "$99.00",
    isContainer: false,
    description: "Dynamic price display - bind to CMS field",
    defaultCommerce: { type: "price", provider: "generic" },
  },
  {
    label: "Pricing Card",
    tag: "div",
    icon: "CreditCard",
    category: "commerce",
    defaultClassName: "flex flex-col rounded-2xl border border-white/10 bg-white/5 p-8 text-center",
    isContainer: true,
    description: "Pricing tier card for pricing pages",
    defaultCommerce: { type: "product", provider: "generic" },
  },
  {
    label: "Pricing Table",
    tag: "div",
    icon: "Table",
    category: "commerce",
    defaultClassName: "grid grid-cols-1 md:grid-cols-3 gap-6",
    isContainer: true,
    description: "Side-by-side pricing comparison",
    defaultCommerce: { type: "collection", provider: "generic" },
  },
  {
    label: "Cart Icon",
    tag: "button",
    icon: "ShoppingCart",
    category: "commerce",
    defaultClassName: "relative p-2 rounded-lg hover:bg-white/10 transition-colors",
    isContainer: false,
    description: "Shopping cart icon with badge",
    defaultCommerce: { type: "cart", provider: "generic" },
  },
  {
    label: "Quantity Selector",
    tag: "div",
    icon: "PlusCircle",
    category: "commerce",
    defaultClassName: "inline-flex items-center rounded-lg border border-white/10 bg-white/5",
    isContainer: true,
    description: "Quantity +/- controls",
    defaultCommerce: { type: "cart", provider: "generic" },
  },

  // ========== SHOPIFY / HYDROGEN ==========
  {
    label: "Shopify Product",
    tag: "div",
    icon: "ShoppingBag",
    category: "commerce",
    defaultClassName: "group flex flex-col gap-3 rounded-xl border border-white/10 bg-white/5 p-4 hover:border-white/20 transition-colors",
    isContainer: true,
    frameworkRequirement: "hydrogen",
    commerceProvider: "shopify",
    componentName: "ProductCard",
    description: "Shopify product with Storefront API",
    defaultCommerce: { type: "product", provider: "shopify" },
  },
  {
    label: "Shopify Collection",
    tag: "div",
    icon: "Grid3X3",
    category: "commerce",
    defaultClassName: "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6",
    isContainer: true,
    frameworkRequirement: "hydrogen",
    commerceProvider: "shopify",
    componentName: "ProductGrid",
    description: "Products from Shopify collection",
    defaultCommerce: { type: "collection", provider: "shopify", limit: 8, sortKey: "BEST_SELLING" },
  },
  {
    label: "Shopify Image",
    tag: "img",
    icon: "ImageIcon",
    category: "commerce",
    defaultClassName: "w-full aspect-square object-cover rounded-lg bg-white/5",
    defaultAttrs: { src: "https://cdn.shopify.com/placeholder.png", alt: "Product image" },
    isContainer: false,
    frameworkRequirement: "hydrogen",
    commerceProvider: "shopify",
    componentName: "ProductImage",
    description: "Optimized Shopify CDN image",
  },
  {
    label: "Shopify Price",
    tag: "span",
    icon: "DollarSign",
    category: "commerce",
    defaultClassName: "text-base font-medium text-white/80",
    defaultTextContent: "$0.00",
    isContainer: false,
    frameworkRequirement: "hydrogen",
    commerceProvider: "shopify",
    componentName: "ProductPrice",
    description: "Shopify Money component",
  },
  {
    label: "Shopify Add to Cart",
    tag: "button",
    icon: "ShoppingCart",
    category: "commerce",
    defaultClassName: "w-full rounded-lg bg-blue-600 px-4 py-3 text-sm font-medium text-white hover:bg-blue-500 transition-colors disabled:opacity-50",
    defaultTextContent: "Add to Cart",
    isContainer: false,
    frameworkRequirement: "hydrogen",
    commerceProvider: "shopify",
    componentName: "AddToCartButton",
    description: "Adds to Shopify cart",
    defaultCommerce: { type: "cart", provider: "shopify" },
  },
  {
    label: "Shopify Buy Now",
    tag: "button",
    icon: "Zap",
    category: "commerce",
    defaultClassName: "w-full rounded-lg bg-white px-4 py-3 text-sm font-medium text-black hover:bg-white/90 transition-colors",
    defaultTextContent: "Buy Now",
    isContainer: false,
    frameworkRequirement: "hydrogen",
    commerceProvider: "shopify",
    componentName: "BuyNowButton",
    description: "Direct Shopify checkout",
    defaultCommerce: { type: "checkout", provider: "shopify" },
  },
  {
    label: "Variant Selector",
    tag: "div",
    icon: "Palette",
    category: "commerce",
    defaultClassName: "flex flex-wrap gap-2",
    isContainer: true,
    frameworkRequirement: "hydrogen",
    commerceProvider: "shopify",
    componentName: "VariantSelector",
    description: "Shopify variant options",
    defaultCommerce: { type: "product", provider: "shopify" },
  },
  {
    label: "Shopify Search",
    tag: "input",
    icon: "Search",
    category: "commerce",
    defaultClassName: "w-full rounded-lg border border-white/10 bg-white/5 px-4 py-3 text-sm text-white placeholder:text-white/40 focus:outline-none focus:ring-2 focus:ring-blue-500/50",
    defaultAttrs: { type: "search", placeholder: "Search products..." },
    isContainer: false,
    frameworkRequirement: "hydrogen",
    commerceProvider: "shopify",
    componentName: "PredictiveSearch",
    description: "Shopify predictive search",
  },

  // ========== STRIPE ==========
  {
    label: "Stripe Checkout",
    tag: "button",
    icon: "CreditCard",
    category: "commerce",
    defaultClassName: "w-full rounded-lg bg-[#635BFF] px-6 py-3 text-sm font-medium text-white hover:bg-[#5851DB] transition-colors",
    defaultTextContent: "Pay with Stripe",
    isContainer: false,
    commerceProvider: "stripe",
    componentName: "StripeCheckoutButton",
    description: "Redirects to Stripe Checkout",
    defaultCommerce: { type: "checkout", provider: "stripe", stripeMode: "payment" },
  },
  {
    label: "Stripe Subscribe",
    tag: "button",
    icon: "RefreshCw",
    category: "commerce",
    defaultClassName: "w-full rounded-lg bg-[#635BFF] px-6 py-3 text-sm font-medium text-white hover:bg-[#5851DB] transition-colors",
    defaultTextContent: "Subscribe",
    isContainer: false,
    commerceProvider: "stripe",
    componentName: "StripeSubscribeButton",
    description: "Stripe subscription checkout",
    defaultCommerce: { type: "checkout", provider: "stripe", stripeMode: "subscription" },
  },
  {
    label: "Stripe Pricing",
    tag: "div",
    icon: "Table",
    category: "commerce",
    defaultClassName: "rounded-2xl border border-[#635BFF]/20 bg-[#635BFF]/5 p-8",
    isContainer: true,
    commerceProvider: "stripe",
    componentName: "StripePricingCard",
    description: "Pricing card with Stripe integration",
    defaultCommerce: { type: "price", provider: "stripe" },
  },

  // ========== PAYPAL ==========
  {
    label: "PayPal Button",
    tag: "div",
    icon: "Wallet",
    category: "commerce",
    defaultClassName: "w-full",
    isContainer: false,
    commerceProvider: "paypal",
    componentName: "PayPalButton",
    description: "PayPal Smart Button",
    defaultCommerce: { type: "checkout", provider: "paypal" },
  },
  {
    label: "PayPal Subscribe",
    tag: "div",
    icon: "RefreshCw",
    category: "commerce",
    defaultClassName: "w-full",
    isContainer: false,
    commerceProvider: "paypal",
    componentName: "PayPalSubscribe",
    description: "PayPal subscription button",
    defaultCommerce: { type: "checkout", provider: "paypal" },
  },

  // ========== SNIPCART (Headless) ==========
  {
    label: "Snipcart Button",
    tag: "button",
    icon: "ShoppingBag",
    category: "commerce",
    defaultClassName: "snipcart-add-item w-full rounded-lg bg-emerald-600 px-6 py-3 text-sm font-medium text-white hover:bg-emerald-500 transition-colors",
    defaultTextContent: "Add to Cart",
    isContainer: false,
    commerceProvider: "snipcart",
    componentName: "SnipcartButton",
    description: "Snipcart add to cart (data attributes)",
    defaultCommerce: { type: "cart", provider: "snipcart" },
  },

  // ========== SMART COMMERCE (data-driven components) ==========
  {
    label: "Smart Product Grid",
    tag: "div",
    icon: "Grid3X3",
    category: "smart-commerce",
    defaultClassName: "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6",
    isContainer: false,
    componentName: "ProductGrid",
    description: "Dynamic product grid with real data",
    defaultCommerce: { type: "collection", provider: "generic", limit: 12, sortKey: "CREATED_AT" },
  },
  {
    label: "Smart Product Card",
    tag: "div",
    icon: "Package",
    category: "smart-commerce",
    defaultClassName: "group flex flex-col gap-3 rounded-xl border border-white/10 bg-white/5 p-4 hover:border-white/20 transition-colors",
    isContainer: false,
    componentName: "ProductCard",
    description: "Single product card with image, title, price",
    defaultCommerce: { type: "product", provider: "generic" },
  },
  {
    label: "Featured Products",
    tag: "div",
    icon: "Star",
    category: "smart-commerce",
    defaultClassName: "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6",
    isContainer: false,
    componentName: "FeaturedProducts",
    description: "Curated featured products section",
    defaultCommerce: { type: "collection", provider: "generic", limit: 4, sortKey: "BEST_SELLING" },
  },
  {
    label: "Category Nav",
    tag: "nav",
    icon: "FolderTree",
    category: "smart-commerce",
    defaultClassName: "flex flex-wrap gap-2",
    isContainer: false,
    componentName: "CategoryNav",
    description: "Product category navigation links",
  },
  {
    label: "Product Search",
    tag: "div",
    icon: "Search",
    category: "smart-commerce",
    defaultClassName: "w-full max-w-md",
    isContainer: false,
    componentName: "ProductSearch",
    description: "Search bar with product suggestions",
  },
  {
    label: "Smart Add to Cart",
    tag: "button",
    icon: "ShoppingCart",
    category: "smart-commerce",
    defaultClassName: "w-full rounded-lg bg-blue-600 px-6 py-3 text-sm font-medium text-white hover:bg-blue-500 transition-colors",
    defaultTextContent: "Add to Cart",
    isContainer: false,
    componentName: "AddToCartButton",
    description: "Add to cart with quantity and variant selection",
    defaultCommerce: { type: "cart", provider: "generic" },
  },
  {
    label: "Cart Summary",
    tag: "div",
    icon: "ShoppingBag",
    category: "smart-commerce",
    defaultClassName: "rounded-xl border border-white/10 bg-white/5 p-6",
    isContainer: false,
    componentName: "CartSummary",
    description: "Mini cart with item count and total",
    defaultCommerce: { type: "cart", provider: "generic" },
  },

  // ========== SMART DASHBOARD (customer account widgets) ==========
  {
    label: "Dashboard Welcome",
    tag: "div",
    icon: "Hand",
    category: "smart-dashboard",
    defaultClassName: "rounded-xl bg-gradient-to-r from-blue-600 to-purple-600 p-6 text-white",
    isContainer: false,
    componentName: "DashboardWelcome",
    description: "Personalized welcome banner with user name",
  },
  {
    label: "Recent Orders",
    tag: "div",
    icon: "ClipboardList",
    category: "smart-dashboard",
    defaultClassName: "rounded-xl border border-white/10 bg-white/5 p-6",
    isContainer: false,
    componentName: "RecentOrders",
    description: "Latest orders with status and tracking",
    defaultCommerce: { type: "customer", provider: "generic" },
  },
  {
    label: "Quick Actions",
    tag: "div",
    icon: "Zap",
    category: "smart-dashboard",
    defaultClassName: "grid grid-cols-2 gap-4",
    isContainer: false,
    componentName: "QuickActions",
    description: "Quick action buttons (orders, settings, support)",
  },
  {
    label: "Account Info",
    tag: "div",
    icon: "User",
    category: "smart-dashboard",
    defaultClassName: "rounded-xl border border-white/10 bg-white/5 p-6",
    isContainer: false,
    componentName: "AccountInfo",
    description: "Customer profile card with avatar and details",
    defaultCommerce: { type: "customer", provider: "generic" },
  },
  {
    label: "Promo Block",
    tag: "div",
    icon: "Gift",
    category: "smart-dashboard",
    defaultClassName: "rounded-xl border border-amber-500/20 bg-amber-500/5 p-6",
    isContainer: false,
    componentName: "PromoBlock",
    description: "Promotional banner or discount code display",
  },

  // ========== ADDITIONAL BLOCKS ==========
  {
    label: "Code Block",
    tag: "pre",
    icon: "Code",
    category: "typography",
    defaultClassName: "bg-gray-900 text-gray-100 p-4 rounded-lg overflow-x-auto font-mono text-sm",
    defaultTextContent: "// Your code here",
    isContainer: false,
  },
  {
    label: "Embed",
    tag: "iframe",
    icon: "Code",
    category: "media",
    defaultClassName: "w-full aspect-video rounded-lg border-0",
    defaultAttrs: { src: "", title: "Embedded content" },
    isContainer: false,
  },
  {
    label: "Select",
    tag: "select",
    icon: "FormInput",
    category: "form",
    defaultClassName: "w-full px-4 py-2 border rounded-md bg-background",
    isContainer: false,
  },
  {
    label: "Checkbox",
    tag: "input",
    icon: "FormInput",
    category: "form",
    defaultClassName: "h-4 w-4 rounded border-gray-300",
    defaultAttrs: { type: "checkbox" },
    isContainer: false,
  },
  {
    label: "Radio",
    tag: "input",
    icon: "FormInput",
    category: "form",
    defaultClassName: "h-4 w-4 rounded-full border-gray-300",
    defaultAttrs: { type: "radio" },
    isContainer: false,
  },
  {
    label: "Table",
    tag: "table",
    icon: "LayoutGrid",
    category: "layout",
    defaultClassName: "w-full border-collapse border border-border",
    isContainer: true,
  },
  {
    label: "Figure",
    tag: "figure",
    icon: "Image",
    category: "media",
    defaultClassName: "my-4",
    isContainer: true,
  },
  {
    label: "Caption",
    tag: "figcaption",
    icon: "AlignLeft",
    category: "media",
    defaultClassName: "text-sm text-muted-foreground mt-2 text-center",
    defaultTextContent: "Image caption",
    isContainer: false,
  },
  {
    label: "Details",
    tag: "details",
    icon: "MousePointerClick",
    category: "interactive",
    defaultClassName: "border border-border rounded-lg p-4",
    isContainer: true,
  },
  {
    label: "Summary",
    tag: "summary",
    icon: "MousePointerClick",
    category: "interactive",
    defaultClassName: "cursor-pointer font-semibold text-lg",
    defaultTextContent: "Click to expand",
    isContainer: false,
  },
]

export function getTemplateByLabel(label: string): BlockTemplate | undefined {
  return BLOCK_TEMPLATES.find((t) => t.label === label)
}

export function getTemplatesByCategory(category: string): BlockTemplate[] {
  return BLOCK_TEMPLATES.filter((t) => t.category === category)
}

export const BLOCK_CATEGORIES = [
  { id: "layout", label: "Layout", icon: "LayoutGrid" },
  { id: "typography", label: "Typography", icon: "Type" },
  { id: "media", label: "Media", icon: "Image" },
  { id: "interactive", label: "Interactive", icon: "MousePointerClick" },
  { id: "form", label: "Form", icon: "FormInput" },
  { id: "commerce", label: "Commerce", icon: "ShoppingCart" },
  { id: "smart-commerce", label: "Smart Commerce", icon: "Store" },
  { id: "smart-dashboard", label: "Dashboard Widgets", icon: "LayoutDashboard" },
] as const

/** Commerce provider metadata for UI display */
export const COMMERCE_PROVIDERS = {
  generic: { label: "Generic", color: "gray", icon: "Package" },
  shopify: { label: "Shopify", color: "green", icon: "ShoppingBag" },
  stripe: { label: "Stripe", color: "purple", icon: "CreditCard" },
  paypal: { label: "PayPal", color: "blue", icon: "Wallet" },
  snipcart: { label: "Snipcart", color: "emerald", icon: "ShoppingCart" },
  medusa: { label: "Medusa", color: "violet", icon: "Package" },
  saleor: { label: "Saleor", color: "indigo", icon: "Store" },
} as const
